In [1]:
import pandas as pd

data={
    "name":["david","daisy","willy","wendy"],
    "age":[21,20,18,9],
    "class":[2,"pending",4,4]
}
df=pd.DataFrame(data)
df

name  age    class
0  david   21        2
1  daisy   20  pending
2  willy   18        4
3  wendy    9        4

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

print(np.arange(10))

[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
#pytho list
#why is numpy so useful and memory efficient
import warnings
warnings.filterwarnings('ignore')
L=range(1000)
%timeit[i**2 for i in L]

UsageError: Line magic function `%timeit[i**2` not found.


In [4]:
a=np.arange(1000)
%timeit a**2

4.08 µs ± 349 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [5]:
#creating arrays in numpy
#1-D
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [6]:
#print dimensions
a.ndim

1

In [7]:
#shape
a.shape

(4,)

In [8]:
len(a)

4

In [9]:
#creating a 2-D, 3-D....array
b=np.array([[0,1,2,3],[4,5,6,7]])
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
b.ndim

2

In [12]:
b.shape

(2, 4)

In [13]:
len(b)#returns the size of the first dimensions

2

In [15]:
#3-D array
c=np.array([[[0,1,2],[3,4,5],[6,7,8]]])
c

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [16]:
c.ndim

3

In [17]:
c.shape

(1, 3, 3)

In [18]:
#functions for creating an array
#using the arange function
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b=np.arange(1,10,2) #start, end(exclusive),step
b

array([1, 3, 5, 7, 9])

In [21]:
#using linespace
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [23]:
#creating a two dimension array with all the valu is one (1)
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#creating a two dimensonal array with all the arrays with zeros(0)
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#creating the identity matrix It is represented by (13X3)
c=np.eye(3) #Return a 2-D array with ones on the diagonal and zeros elswhere
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
d=np.eye(3,2)#3 is a number of rows, 2 is number of columns index of diagonal start with zero
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [28]:
#creatin an array using the diag
a=np.diag([1,2,3,4])#construct a diagonal array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [29]:
np.diag(a)#extract diagonal

array([1, 2, 3, 4])

In [31]:
#create an array using random
#creating an array of the given shape and populate through the random sample from a uniform distribution

a=np.random.rand(4)
a

array([0.77264936, 0.50318847, 0.67597847, 0.73878282])

In [33]:
a=np.random.randn(4)#Returns a sample (or samples) from the "standard normal" distribution. 
a

array([-1.54460275,  0.59407062,  1.13874458,  1.05045042])

In [34]:
#BASIC DATA TYPES IN NUMPY
a=np.arange(10)
a.dtype

dtype('int32')

In [35]:
#you can explicity state the data type of your own
a=np.arange(10,dtype='float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [36]:
#the default data type is float for zeros and ones functions
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [37]:
#other data type
d=np.array([1+2j,2+4j])
d.dtype

dtype('complex128')

In [38]:
b=np.array([True,False,True,False])
print(b.dtype)

bool


In [39]:
s=np.array(["david","dasiy","willy","wendy"])
s.dtype

dtype('<U5')

In [40]:
#INDEXING AND SLICING AN ARRAY
a=np.arange(10)
a[5]

5

In [46]:
#for multidimensional array
a=np.diag([1,2,3])
print(a)
a[2,2]

[[1 0 0]
 [0 2 0]
 [0 0 3]]


3

In [43]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [47]:
#SLICING
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a[1:8:2] #start,end(exclusive),step

array([1, 3, 5, 7])

In [ ]:
#for reversing the string using this function